# Generated by Django 2.1.5 on 2019-02-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='code', max_length=8)),
                ('img_01', models.FileField(upload_to='./upload/')),
                ('img_02', models.FileField(upload_to='./upload/')),
                ('img_03', models.FileField(upload_to='./upload/')),
                ('img_04', models.FileField(upload_to='./upload/')),
                ('img_05', models.FileField(upload_to='./upload/')),
                ('img_06', models.FileField(upload_to='./upload/')),
                ('img_07', models.FileField(upload_to='./upload/')),
                ('img_08', models.FileField(upload_to='./upload/')),
                ('img_09', models.FileField(upload_to='./upload/')),
                ('img_10', models.FileField(upload_to='./upload/')),
                ('img_11', models.FileField(upload_to='./upload/')),
                ('img_12', models.FileField(upload_to='./upload/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
