# Generated by Django 2.1.5 on 2019-02-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20190215_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawimg',
            name='img_01',
        ),
        migrations.RemoveField(
            model_name='rawimg',
            name='img_02',
        ),
        migrations.RemoveField(
            model_name='rawimg',
            name='img_03',
        ),
        migrations.RemoveField(
            model_name='rawimg',
            name='img_04',
        ),
        migrations.RemoveField(
            model_name='rawimg',
            name='img_05',
        ),
        migrations.RemoveField(
            model_name='rawimg',
            name='img_06',
        ),
        migrations.RemoveField(
            model_name='rawimg',
            name='img_07',
        ),
        migrations.RemoveField(
            model_name='rawimg',
            name='img_08',
        ),
        migrations.RemoveField(
            model_name='rawimg',
            name='img_09',
        ),
        migrations.RemoveField(
            model_name='rawimg',
            name='img_10',
        ),
        migrations.RemoveField(
            model_name='rawimg',
            name='img_11',
        ),
        migrations.RemoveField(
            model_name='rawimg',
            name='img_12',
        ),
    ]
